version: "3.9"

services:
  chain:
    image: ghcr.io/allinbits/cosmos-cash:v2.1.0
  resolver:
    image: ghcr.io/allinbits/cosmos-cash-resolver:main
    environment:
      - GRPC_SERVER_ADDRESS=chain:9090
      - LISTEN=:2109
    depends_on:
      - chain
  webhook-relayer:
    build: ./webhook-relayer/.
    # command: python manage.py runserver 0.0.0.0:8000
    environment:
      - LISTEN=:2110
  agent-bob:
    image: ghcr.io/hyperledger/aries-framework-go:0.1.7
    environment:
      - ARIESD_API_HOST=:8080
      - ARIESD_DEFAULT_LABEL=/bobAgent
      - ARIESD_LOG_LEVEL=DEBUG
      - ARIESD_INBOUND_HOST:8081
      - ARIESD_WEBHOOK_URL=webhook-relayer:2110/wh/bob
      - ARIESD_HTTP_RESOLVER=resolver:2109/identifier/aries
  agent-alice:
    image: ghcr.io/hyperledger/aries-framework-go:0.1.7
    environment:
      - ARIESD_API_HOST=:8080
      - ARIESD_DEFAULT_LABEL=aliceAgent
      - ARIESD_LOG_LEVEL=DEBUG
      - ARIESD_INBOUND_HOST:8081
      - ARIESD_WEBHOOK_URL=webhook-relayer:2110/wh/alice
      - ARIESD_HTTP_RESOLVER=resolver:2109/identifier/aries
  agent-regulator:
    image: ghcr.io/hyperledger/aries-framework-go:0.1.7
    environment:
      - ARIESD_API_HOST=:8080
      - ARIESD_DEFAULT_LABEL=regulatorAgent
      - ARIESD_LOG_LEVEL=DEBUG
      - ARIESD_INBOUND_HOST:8081
      - ARIESD_WEBHOOK_URL=webhook-relayer:2110/wh/regulator
      - ARIESD_HTTP_RESOLVER=resolver:2109/identifier/aries
  agent-issuer:
    image: ghcr.io/hyperledger/aries-framework-go:0.1.7
    environment:
      - ARIESD_API_HOST=:8080
      - ARIESD_DEFAULT_LABEL=issuerAgent
      - ARIESD_LOG_LEVEL=DEBUG
      - ARIESD_INBOUND_HOST:8081
      - ARIESD_WEBHOOK_URL=webhook-relayer:2110/wh/issuer
      - ARIESD_HTTP_RESOLVER=resolver:2109/identifier/aries
  agent-eidas:
    image: ghcr.io/hyperledger/aries-framework-go:0.1.7
    environment:
      - ARIESD_API_HOST=:8080
      - ARIESD_DEFAULT_LABEL=eidasAgent
      - ARIESD_LOG_LEVEL=DEBUG
      - ARIESD_INBOUND_HOST:8081
      - ARIESD_WEBHOOK_URL=webhook-relayer:2110/wh/eidas
      - ARIESD_HTTP_RESOLVER=resolver:2109/identifier/aries
